### PR TITLE
FreeBSD build

### PR DESCRIPTION
**Pull request by Viste**
**Description**
For now build on freebsd is broken in this PR i plan to get it works again

**Todo / Checklist**
- [x] Target is branch develop.
- [x] Detailed description about this pull request.
- [x] Checked AE-Coding standards.

**Tests Performed:** 
- [] Build AE.
- [] Server startup.
- [] Log into world.

### CODE REVIEW

**Comment by schnek** [comment]
screenshot successful build 😁

**Comment by Viste** [comment]
> screenshot successful build 😁

for now only shared build successful

**Comment by Viste** [comment]
stop for 1 day, need to setup freebsd on bare metal server, my vds is hangs on linking( low RAM)

**Comment by Zyres** [comment]
Hey @Viste glad to see you here :-)

Please check out your target branch for this PR
image

We work on branch develop for all PRs and changes.

**Comment by Viste** [comment]
> Hey @Viste glad to see you here :-)
> 
> Please check out your target branch for this PR
> image
> 
> We work on branch develop for all PRs and changes.

ok i swith  bransh end tonight rebase my fork branch to develop.
Ty for explanation, I chose master because I doubted master or develop, ans pick master because of all other emu use master as native develop branch

**Pull request closed without merging**
