### PR TITLE
Wrath of lich king dungeons and raids cell loading related to #817

### PR DESCRIPTION
**Pull request by Razfury**
**Description**

This PR is just for the wrath dungeons and raids to enable cells in them. Thanks to @aaron02 for his adding of updating cells in the Magtheridons lair i decided to do them for wrath dungeons and raids. I will open up seperate PR for each expansion.

**Todo / Checklist**
- [x] Target is branch develop.
- [x] Detailed description about this pull request.
- [x] Checked AE-Coding standards.

**Tests Performed:** 
- [x] Build AE.
- [x] Server startup.
- [x] Log into world.

### CODE REVIEW

**Comment by aaron02** [comment]
you can skip gruuls lair the reworked script is nearly finished :)

**Comment by Razfury** [comment]
Sweet, thanks for the update bud.

**Comment by Zyres** [comment]
@Razfury Thank you, I guess this PR is finished? :-)

**Comment by Razfury** [comment]
@Zyres That is correct i'm opening up seperate PRs for each expansion set.

**Review by Appled — APPROVED** [review]

**Pull request merged**
