### PR TITLE
Add base cataclysm dungeon and raid files for development

### PR DESCRIPTION
**Pull request by Razfury**
**Description**

This adds the base development files for the cataclysm expansion for dungeons + raids.

**Todo / Checklist**
- [x] Target is branch develop.
- [x] Detailed description about this pull request.
- [x] Checked AE-Coding standards.

**Tests Performed:** 
- [x] Build AE.
- [x] Server startup.
- [x] Log into world.

### CODE REVIEW

**Comment by Razfury** [comment]
corrected incorrect map names.

**Review by Appled — APPROVED** [review]

**Review by Appled — COMMENTED** [review]
On a second note why are you including Pet.h in every instance script cpp file?

**Comment by Razfury** [comment]
@Appled @Zyres This has been fixed.

**Review by Appled — APPROVED** [review]

**Comment by Appled** [comment]
You should jump in the Discord server 😃

**Pull request merged**
