### PR TITLE
Classic - corrected entrance to the world. 

### PR DESCRIPTION
**Pull request by schnek**
**Todo / Checklist**
- [x] Target is branch develop.
- [x] Detailed description about this pull request.
- [x] Checked AE-Coding standards.

**Tests Performed:** 
- [x] Server startup.
- [x] Log into world.

**Multiversion Ingame Tests Performed:**
- [x] Classic

### CODE REVIEW

**Comment by Appled** [comment]
Why do you remove health regeneration from Classic?

**Comment by schnek** [comment]
Classic support is made only so that you can enter the world. these changes allow you to enter the world again.

**Comment by Appled** [comment]
Does it crash on world enter without these changes?

**Comment by schnek** [comment]
Yes. to put it in more detail, support for the classic is made only as an entrance to the game. everything interfering with this input was turned off. and added a comment. ` #if VERSION_STRING >= TBC // support classic`

**Comment by aaron02** [comment]
whats wrong with classic i just downloaded client and logged in world just fine ?

**Comment by schnek** [comment]
Now maybe this is due to Lua scripts (I’ll check without them now)

**Comment by aaron02** [comment]
alright ;)

**Comment by schnek** [comment]
image
I'm closing

**Pull request closed without merging**
