### PR TITLE
MMAPs: Update recastnavigation

### PR DESCRIPTION
**Pull request by schnek**
- [x] Update recastnavigation
- [x] Update mmap tools

### CODE REVIEW

**Comment by Evairfairy** [comment]
Hello,

Thank you for your merge request. We will review it as soon as possible, however due to the size of it this may take some time.

Thanks

**Comment by schnek** [comment]
@Evairfairy need more tests

**Comment by Evairfairy** [comment]
@schnek If your commits aren't ready for merging, please don't open a pull request for them.

Is your commit ready for merging?

**Comment by schnek** [comment]
yes, it is ready

**Comment by Zyres** [comment]
@schnek finished? If yes I would start to test it.

**Comment by Appled** [comment]
@schnek can you fix mmaps extractor after this? 😄 I mean it takes way too long to extract mmaps atm

**Comment by schnek** [comment]
@Zyres check the work

**Comment by schnek** [comment]
@Appled  for cataclysm will be even longer

**Comment by Zyres** [comment]
WotLK: no map exp. Check out Who List (Always City)

**Pull request merged**
