### PR TITLE
Fixed some data loads

### PR DESCRIPTION
**Pull request by Lectro**
* Fixed most cases where memory is leaked
    * Fixed possible failures with STL functions misstatch (for example:
    std::count, http://www.cplusplus.com/reference/algorithm/count/)

### CODE REVIEW

**Comment by Lectro** [comment]
This actually reduced memory usage like 150 MB

**Comment by Zyres** [comment]
The reduced memory usage is not "like 150MB" with your changes. Process Memory is nearly the same and the RAM reduced around 200 KB on my machine.

**Comment by Lectro** [comment]
on my machine it lost that amount, mostly was testing on linux

**Comment by Zyres** [comment]
There is no possible mismatch between locale count vars and std::count since we removed "using namespace std" from all files. But I agree that we should rename these vars.

**Comment by Lectro** [comment]
i know but just in case... just old school practises on variables naming - no system used names!

**Pull request merged**
