### PR TITLE
Resolved errors in cmake / added comments

### PR DESCRIPTION
**Pull request by schnek**
Removed active triggers they are not used
Increased maximum build id 48107, 12555
Removed std::string LogFileName, bool bLogChat - not used 
Renamed men -> man

**Description**

**Todo / Checklist**
- [x] Target is branch develop.
- [x] Detailed description about this pull request.
- [x] Checked AE-Coding standards.

**Tests Performed:** 
- [x] Build AE with "TREAT_WARNINGS_AS_ERRORS" flag turned on.
- [x] Server startup.
- [x] Log into world.

**Multiversion Ingame Tests Performed:**
-  Classic
- TBC
- [x] WotLK
- [x] Cata

### CODE REVIEW

**Review by Appled — COMMENTED** [review]
I don't think deleting those spawns is a good idea. They might be required for some quest or event.

**Comment by schnek** [comment]
> I don't think deleting those spawns is a good idea. They might be required for some quest or event.

I don't think they'll ever be here, but if so you can use the option...

``
UPDATE `creature_properties` SET `invisibility_type` = 15 WHERE `entry`IN(.......npc id.......);
``

**Comment by Appled** [comment]
> 
> `` UPDATE `creature_properties` SET `invisibility_type` = 15 WHERE `entry`IN(.......npc id.......); ``
That would be a much better option

**Comment by schnek** [comment]
gm flag
image

normal flag
image


the only thing that I don't like about this option is that if you look at the water you will see the movement of npc (triggers)
image

**Review by Appled — APPROVED** [review]

**Comment by Appled** [comment]
> the only thing that I don't like about this option is that if you look at the water you will see the movement of npc (triggers)

Yeah, probably they shouldn't move at all but that is just a small cosmetic issue 😉

**Pull request merged**
