### PR TITLE
[Build] Mac OS X

### PR DESCRIPTION
**Pull request by Viste**
**Description**
Now build on Mac OS X Big sur (11.4) fails in this PR it will be fixed

**Todo / Checklist**
- [x] Target is branch develop.
- [x] Detailed description about this pull request.
- [x] Checked AE-Coding standards.

**Tests Performed:** 
- [] Build AE.
- [] Server startup.
- [] Log into world.

Check out the requirements for OpenSSL here: https://ascemu.github.io/Wiki/docs/installation/windows/

### CODE REVIEW

**Comment by Zyres** [comment]
Oh wow, looks like we will remove the old openssl stuff from our shipped dependencies :-)

**Comment by Viste** [comment]
> Oh wow, looks like we will remove the old openssl stuff from our shipped dependencies :-)

yes ;) but idk how many days it takes, because i have very little free time at the moment. :(

**Comment by Zyres** [comment]
> > Oh wow, looks like we will remove the old openssl stuff from our shipped dependencies :-)
> 
> yes ;) but idk how many days it takes, because i have very little free time at the moment. :(

No problem, take your time :-)

**Comment by Zyres** [comment]
@Viste Hope you are okay :-)

**Comment by Viste** [comment]
> @Viste Hope you are okay :-)

Now yes ;) 
But a week and a half ago, two weeks sick with covid and still recovering, I don't know when i finish with PR. in few days make a update i guess

**Comment by Zyres** [comment]
> there are 2 news one good another bad
> 
> 1. cmake sees the established ssl. =)
>    image
> 2. the build for windows has not been fixed yet before the end =(
> 
> ```
> if (NOT WIN32) #sch: need a fix for windows
> include(${CMAKE_SOURCE_DIR}/cmake/CheckSystem.cmake)
> endif()
> ```

check the latest changes and give me feedback if your problems are solved :-)

**Comment by schnek** [comment]
can be  Merge

**Comment by schnek** [comment]
stop

**Review by Appled — COMMENTED** [review]
One more question, why there are two SQL updates removed in this PR from sql/world/updates?

**Comment by schnek** [comment]
by the way, they need to be restored

**Review by Appled — APPROVED** [review]
👍

**Comment by schnek** [comment]
🎉

**Pull request merged**
